#! /usr/bin/env python
"""Streamlit live demo for CLINIGUARD – LightGBM fusion model.

This interactive app loads the trained ``cliniguard_model.joblib`` and the
corresponding ``cliniguard_scaler.joblib`` files that were generated by the
pipeline (see ``cliniguard_pipeline.py``).  Users can type a medical question
and an answer, and the app will compute the four detection signals, the risk
probability, and a colour‑coded label (GREEN / AMBER / RED).

The UI follows a premium dark‑mode aesthetic with smooth gradients and
micro‑animations – perfect for a polished demo.
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd
import math

# Page config – must be the first Streamlit command

from pathlib import Path

# ---------------------------------------------------------------------------
# Load the model & scaler – they live in the same directory as this script.
# ---------------------------------------------------------------------------
MODEL_PATH = Path(__file__).parent / "cliniguard_model.joblib"
SCALER_PATH = Path(__file__).parent / "cliniguard_scaler.joblib"

@st.cache_resource

def load_artifacts():
    model = joblib.load(MODEL_PATH)
    scaler = joblib.load(SCALER_PATH)
    return model, scaler

model, scaler = load_artifacts()

# ---------------------------------------------------------------------------
# Re‑define the four formula functions (lightweight copy – avoids a heavy import).
# ---------------------------------------------------------------------------
DRUG_TERMS = {
    "mg",
    "dose",
    "dosage",
    "tablet",
    "capsule",
    "injection",
    "oral",
    "iv",
    "intravenous",
    "amoxicillin",
    "ibuprofen",
    "metformin",
    "insulin",
    "aspirin",
    "atorvastatin",
    "omeprazole",
    "paracetamol",
    "acetaminophen",
    "warfarin",
    "morphine",
    "prednisone",
    "antibiotic",
    "medication",
    "drug",
    "prescribe",
    "contraindication",
    "side",
    "effect",
    "adverse",
}

CONTEXT_TERMS = {
    "patient",
    "allergy",
    "allergic",
    "age",
    "weight",
    "pediatric",
    "adult",
    "vital",
    "history",
    "medication",
    "diagnosis",
    "symptom",
    "report",
    "female",
    "male",
    "blood pressure",
    "heart rate",
    "temperature",
    "chronic",
    "acute",
    "clinical",
    "contraindication",
}

UNCERTAIN_WORDS = {
    "maybe",
    "possibly",
    "might",
    "could",
    "uncertain",
    "unclear",
    "unknown",
    "approximately",
    "seems",
    "appears",
    "suggest",
    "perhaps",
    "likely",
    "probably",
    "assume",
    "think",
    "believe",
    "estimate",
    "roughly",
    "sometimes",
    "often",
}

def tokenize(text):
    return text.lower().split() if isinstance(text, str) else []

# --- Formula 1: Med‑ISP ----------------------------------------------------
def med_isp(text):
    words = tokenize(text)
    if not words:
        return 1.0
    hits = sum(1 for w in words if any(t in w for t in DRUG_TERMS))
    density = hits / max(len(words) * 0.05, 1)
    return round(1.0 - min(density, 1.0), 4)

# --- Formula 2: C‑AAS ----------------------------------------------------
def c_aas(text):
    words = tokenize(text)
    if not words:
        return 1.0
    hits = sum(1 for w in words if any(t in w for t in CONTEXT_TERMS))
    density = hits / max(len(words) * 0.04, 1)
    return round(1.0 - min(density, 1.0), 4)

# --- Formula 3: Med‑EEM ---------------------------------------------------
def med_eem(text):
    words = tokenize(text)
    n = len(words)
    if n == 0:
        return 0.0
    u_hits = sum(1 for w in words if any(u in w for u in UNCERTAIN_WORDS))
    p = u_hits / n
    eps = 1e-9
    H = -(p * math.log2(p + eps) + (1 - p) * math.log2(1 - p + eps))
    return round(min(H * (1 + p), 1.0), 4)

# --- Formula 4: CDT -------------------------------------------------------
def _wvec(text):
    freq = {}
    for w in tokenize(text):
        freq[w] = freq.get(w, 0) + 1
    return freq

def cdt(answer, question):
    v1, v2 = _wvec(question), _wvec(answer)
    vocab = set(v1) | set(v2)
    if not vocab:
        return 0.5
    dot = sum(v1.get(w, 0) * v2.get(w, 0) for w in vocab)
    m1 = math.sqrt(sum(x ** 2 for x in v1.values()))
    m2 = math.sqrt(sum(x ** 2 for x in v2.values()))
    if m1 == 0 or m2 == 0:
        return 0.5
    return round(1.0 - dot / (m1 * m2), 4)

# ---------------------------------------------------------------------------
# Helper for colour‑coded label
# ---------------------------------------------------------------------------
def risk_label(score: float) -> str:
    if score < 0.35:
        return "🟢 GREEN (Safe)"
    elif score < 0.65:
        return "🟡 AMBER (Review needed)"
    else:
        return "🔴 RED (High‑risk hallucination)"

# ---------------------------------------------------------------------------
# Streamlit UI – premium dark theme with gradient background
# ---------------------------------------------------------------------------


# Custom CSS for dark‑mode gradient and smooth hover effects
st.markdown(
    """
    <style>
    body {
        background: linear-gradient(135deg, #1e1e2f, #2c2c3e);
        color: #e0e0ff;
        font-family: 'Inter', sans-serif;
    }
    .stButton>button {
        background: #4e79a7;
        color: white;
        border-radius: 8px;
        padding: .5rem 1.5rem;
        font-weight: 600;
        transition: transform 0.1s ease, background 0.2s ease;
    }
    .stButton>button:hover {
        background: #74b3ff;
        transform: translateY(-2px);
    }
    .stTextInput>div>div>input {
        background: #2c2c3e;
        color: #e0e0ff;
        border: 1px solid #4e79a7;
        border-radius: 5px;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("🏥 CLINIGUARD – Live Hallucination‑Risk Demo")
st.markdown(
    """
    **Provide a medical question and an answer.**
    The app computes four detection signals, feeds them to the **LightGBM**
    fusion model, and returns a risk probability together with a colour‑coded
    label.
    """
)

question = st.text_area("🗣️ Question", height=80, placeholder="e.g., What is the recommended dosage of amoxicillin for a 5‑year‑old?")
answer = st.text_area("✍️ Answer", height=150, placeholder="Type the model’s answer here …")

if st.button("🔍 Evaluate Risk"):
    if not question.strip() or not answer.strip():
        st.warning("Please fill in both the question and the answer.")
    else:
        # Compute signals
        sig_vals = np.array([
            med_isp(answer),
            c_aas(answer),
            med_eem(answer),
            cdt(answer, question),
        ]).reshape(1, -1)
        sig_scaled = scaler.transform(sig_vals)
        prob = model.predict_proba(sig_scaled)[0, 1]
        label = risk_label(prob)

        # Display results in a nice card
        st.markdown("---")
        col1, col2 = st.columns([2, 1])
        with col1:
            st.subheader("🔢 Signals")
            st.write(
                f"* **Med‑ISP** : {sig_vals[0,0]:.3f}\n"
                f"* **C‑AAS**  : {sig_vals[0,1]:.3f}\n"
                f"* **Med‑EEM**: {sig_vals[0,2]:.3f}\n"
                f"* **CDT**    : {sig_vals[0,3]:.3f}"
            )
        with col2:
            st.subheader("📈 Risk")
            st.metric(label=label, value=f"{prob:.4f}")
        st.markdown("---")
        st.success("**Assessment complete.** Use the colour label to decide if the answer needs review.")

st.caption("*All calculations use the same 4 formula modules described in the project documentation.*")

"""# End of file"""
